############################################################
# Dockerfile to build Apache Php7
# Based on Debian Jessie
############################################################

FROM debian:jessie
MAINTAINER Vincent Montet

# Disable interactive functions
ENV DEBIAN_FRONTEND noninteractive

# Locale
ENV LOCALE fr_CH.UTF-8

# PHP Timezone
ENV TZ=Europe/Zurich


################## BEGIN INSTALLATION ######################

#Install basic tool
RUN \
  apt-get update && \
  apt-get install -y \
  curl \
  wget \
  git \
  apt-utils


#add depo for php7
RUN echo "deb http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list.d/dotdeb.org.list && \
    echo "deb-src http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list.d/dotdeb.org.list && \
    wget -O- http://www.dotdeb.org/dotdeb.gpg | apt-key add -

#Install php7 and some lib
RUN \
  apt-get update && \
  apt-get install -y \
  apache2 \
  vim \
  locales \
  iptables \
  php7.0 \
  php7.0-dev \
  libapache2-mod-php7.0 \
  php7.0-common \
  php-pear \
  php7.0-curl \
  php7.0-gd \
  php7.0-imagick \
  php7.0-intl \
  php7.0-mcrypt \
  php7.0-pgsql \
  php7.0-opcache \
  php7.0-mysql \
  php7.0-mongodb \
  php7.0-bz2 \
  && apt-get clean


#Active pdo_mysql
RUN phpenmod pdo_mysql

RUN a2enmod rewrite

##################### INSTALLATION END #####################

# Expose the default port
EXPOSE 80

# Configure executable.
ENTRYPOINT ["/bin/bash"]

# Define default command.
CMD ["apache2ctl","-D","FOREGROUND"]
